spring.application.name=bepsachviet_be
spring.datasource.url=jdbc:mysql://localhost:3306/bepsachviet
spring.datasource.username=root
spring.datasource.password=hung123321@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
