# Database Configuration
spring.datasource.url=jdbc:mysql://mysql-d1883b2-nguyencuongaq1-1de1.i.aivencloud.com:27306/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- SERVER CONFIG ---
server.servlet.context-path=/api/v1.0

# --- JWT SECURITY ---
jwt.secret.key=${JWT_SECRET_KEY}

aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-southeast-2
aws.bucket.name=bepsachviet-s3-doan

momo.partnerCode=${MOMO_PARTNER_CODE}
momo.accessKey=${MOMO_ACCESS_KEY}
momo.secretKey=${MOMO_SECRET_KEY}
momo.endpoint=${MOMO_ENDPOINT}
momo.redirectUrl=${MOMO_REDIRECT_URL}
momo.ipnUrl=${MOMO_IPN_URL}
momo.requestType=captureWallet